
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shuvon
 */
public class ui_manager_detail extends javax.swing.JFrame {

    /**
     * Creates new form ui_manager_detail
     */
    public ui_manager_detail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterManager = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        DeleteManager = new javax.swing.JButton();
        jmid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchManager = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ShowManager = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegisterManager.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        RegisterManager.setText("Register Manager");
        RegisterManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterManagerActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        DeleteManager.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DeleteManager.setText("Delete Manager");
        DeleteManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteManagerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Manager Id");

        SearchManager.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        SearchManager.setText("Search Manager");
        SearchManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchManagerActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FullName", "UserName", "Gender", "Age", "Address", "Mobile", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ShowManager.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ShowManager.setText("Show Manager List");
        ShowManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowManagerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manager Detail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterManager)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jmid, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteManager)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchManager)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowManager)
                .addGap(277, 277, 277))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteManager, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchManager, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(ShowManager, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(RegisterManager, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterManagerActionPerformed
        // TODO add your handling code here:
        new ui_4_managerlist().setVisible(true);
        new ui_manager_detail().setVisible(false);
        dispose();

    }//GEN-LAST:event_RegisterManagerActionPerformed

    private void ShowManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowManagerActionPerformed
        // TODO add your handling code here:
        try {
            //int count=0;
            //count++;
            //System.out.println(count);
            String conn = "com.mysql.cj.jdbc.Driver";
            Class.forName(conn);
            String s = "jdbc:mysql://localhost:3306/AgriFarm";
            String rt = "root";
            Connection con = DriverManager.getConnection(s, rt, "");
            String sql = "select * from managerlist";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            String id, name, user, age, gender, add, mob,pass;
            DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
            tbl.getDataVector().removeAllElements();
            while (rs.next()) {
                id = String.valueOf(rs.getInt("MID"));
                name = rs.getString("FullName");
                user = rs.getString("UserName");
                gender = rs.getString("Gender");
                age = rs.getString("Age");
                add = rs.getString("Address");
                mob = rs.getString("Mobile");
                pass=rs.getString("Password");

                String tdata[] = {id, name, user, gender, age, add, mob,pass};
                //DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
                //tbl.getDataVector().removeAllElements();
                tbl.addRow(tdata);
            }
        } catch (Exception ex) {
            Logger.getLogger(ui_4_managerlist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ShowManagerActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new ui_2_admin().setVisible(true);
        new ui_manager_detail().setVisible(false);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void SearchManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchManagerActionPerformed
        // TODO add your handling code here:
        try {
            String conn = "com.mysql.cj.jdbc.Driver";
            Class.forName(conn);
            String s = "jdbc:mysql://localhost:3306/AgriFarm";
            String rt = "root";
            Connection con = DriverManager.getConnection(s, rt, "");

            String sql = "select * from managerlist where MID=?";

            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            String id = jmid.getText();
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();
            String iid, name, user, age, gender, add, mob,pass;
            if(rs.next()) {
                iid = String.valueOf(rs.getInt("MID"));
                name = rs.getString("FullName");
                user = rs.getString("UserName");
                gender = rs.getString("Gender");
                age = rs.getString("Age");
                add = rs.getString("Address");
                mob = rs.getString("Mobile");
                pass=rs.getString("Password");

                String tdata[] = {iid, name, user, gender, age, add, mob,pass};
                DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
                tbl.getDataVector().removeAllElements();
                tbl.addRow(tdata);
            }
            else
                JOptionPane.showMessageDialog(null, "manager hasnot been register yet");
        } catch (Exception ex) {
            Logger.getLogger(ui_4_managerlist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchManagerActionPerformed

    private void DeleteManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteManagerActionPerformed
        // TODO add your handling code here:
        try {
            String conn = "com.mysql.cj.jdbc.Driver";
            Class.forName(conn);
            String s = "jdbc:mysql://localhost:3306/AgriFarm";
            String rt = "root";
            Connection con = DriverManager.getConnection(s, rt, "");
            
            String sql = "delete from managerlist where MID=?";
            
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            String iid=jmid.getText();
            ps.setString(1,iid);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Deleted a Manager");
            sql="select * from managerlist";
            ps=con.prepareStatement(sql);
            
            ResultSet rs=ps.executeQuery();
            
             String id, name, user, age, gender, add, mob,pass;
            DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
            tbl.getDataVector().removeAllElements();
            while (rs.next()) {
                id = String.valueOf(rs.getInt("MID"));
                name = rs.getString("FullName");
                user = rs.getString("UserName");
                gender = rs.getString("Gender");
                age = rs.getString("Age");
                add = rs.getString("Address");
                mob = rs.getString("Mobile");
                pass=rs.getString("Password");

                String tdata[] = {id, name, user, gender, age, add, mob,pass};
                //DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
                //tbl.getDataVector().removeAllElements();
                tbl.addRow(tdata);
            }
            
        }
        catch (Exception ex) {
            Logger.getLogger(ui_4_managerlist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui_manager_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui_manager_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui_manager_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui_manager_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui_manager_detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton DeleteManager;
    private javax.swing.JButton RegisterManager;
    private javax.swing.JButton SearchManager;
    private javax.swing.JButton ShowManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jmid;
    // End of variables declaration//GEN-END:variables
}
